[package]
name = "satispay"
version = "0.1.0"
authors = ["Eugenio Tampieri <eugenio@eutampieri.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12"
serde_json = "1.0"
rsa = "0.3"
ureq = "1.3"
serde = {version = "1.0", features = ["derive"]}
sha2 = "0.9"
chrono = {version = "0.4", features = ["serde"]}
urlencoding = "1.1"
